[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'godlygeek/tabular'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'joshdick/onedark.vim'


